In [57]:
import requests 

def marketcap(date = None) : 
    if date == None : 
        date = datetime.today().strftime('%Y%m%d')
    
    # STEP 1 : Generate OTP (One-Time Passcode)

    OTP_url = "http://marketdata.krx.co.kr/contents/COM/GenerateOTP.jspx"
    OTP_data = {
        'name' : 'fileDown' ,
        'filetype' : 'xls' ,
        'url' : 'MKD/04/0404/04040200/mkd04040200_01' ,
        'market_gubun': 'ALL', 
        'indx_ind_cd' : 'ALL', 
        'sect_tp_cd' : 'ALL' , 
        'schdate' : date , 
        'pagePath' : '/contents/MKD/04/0404/04040200/MKD04040200.jsp'
    }
     
    r = requests.post(OTP_url , OTP_data)
    code = r.content 
    
     # STEP 02: download
    down_url = 'http://file.krx.co.kr/download.jspx'
    down_data = {
        'code': code,
    }
    
    r = requests.post(down_url, down_data) 
    df = pd.read_excel(BytesIO(r.content) , header = 0 , thousands= ',')
    return df

In [59]:
marketcap(date).head()
a = marketcap(date)

In [60]:
a.head()

,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수(천주),외국인 보유주식수,외국인 지분율(%)
0,005930,삼성전자,1749000,3000,0.2,310707,542448277092,1740000,1753000,1733000,246048160413000,16.74,140679337,71616831,50.91
1,000660,SK하이닉스,44200,1300,3.0,3491185,153722631725,43000,44400,43000,32177704533000,2.19,728002365,374928937,51.50
2,005380,현대차,132000,-1000,-0.8,478362,63868123000,133000,135500,132000,29076495228000,1.98,220276479,95229553,43.23
3,015760,한국전력,44500,-2000,-4.3,2557351,114644555000,46100,46150,44300,28567401426500,1.94,641964077,202512152,31.55
4,005935,삼성전자우,1361000,5000,0.4,50781,69712003688,1356000,1383000,1342000,27918774147000,1.90,20513427,16027181,78.13

In [85]:
# 종목찾기 : 현대차
security = [a.loc[num] for num in range(len(a)) if a.loc[num][1] == '현대차'] 
security

[종목코드                  005380
 종목명                      현대차
 현재가                   132000
 대비                     -1000
 등락률                     -0.8
 거래량                   478362
 거래대금             63868123000
 시가                    133000
 고가                    135500
 저가                    132000
 시가총액          29076495228000
 시가총액비중(%)               1.98
 상장주식수(천주)          220276479
 외국인 보유주식수           95229553
 외국인 지분율(%)             43.23
 Name: 2, dtype: object]

In [86]:
# 거래대금 내림차순 정리 
a_vol = a.sort_values(ascending = False, by  = ['거래대금'])
a_vol.head(n = 20)

,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수(천주),외국인 보유주식수,외국인 지분율(%)
0,005930,삼성전자,1749000,3000,0.2,310707,542448277092,1740000,1753000,1733000,246048160413000,16.74,140679337,71616831,50.91
1,000660,SK하이닉스,44200,1300,3.0,3491185,153722631725,43000,44400,43000,32177704533000,2.19,728002365,374928937,51.50
30,207940,삼성바이오로직스,144500,-9500,-6.2,852285,125615900750,153500,154000,144000,9560842500000,0.65,66165000,7403575,11.19
3,015760,한국전력,44500,-2000,-4.3,2557351,114644555000,46100,46150,44300,28567401426500,1.94,641964077,202512152,31.55
46,036570,엔씨소프트,245000,-27000,-9.9,443257,110059787000,267000,267000,240500,5372610390000,0.37,21929022,8405596,38.33
9,005490,POSCO,251000,1500,0.6,323869,81580045500,249500,254000,249500,21883895585000,1.49,87186835,45436667,52.11
5,035420,NAVER,764000,-34000,-4.3,103862,80896272404,790000,798000,764000,25183486756000,1.71,32962679,20013972,60.72
17,096770,SK이노베이션,153500,1000,0.7,481172,75263020000,159500,160500,153500,14193464074000,0.97,92465564,37615867,40.68
1606,081150,티플랙스,2745,240,9.6,25632720,73048415655,2650,3080,2630,55949180175,0.00,20382215,342554,1.68
4,005935,삼성전자우,1361000,5000,0.4,50781,69712003688,1356000,1383000,1342000,27918774147000,1.90,20513427,16027181,78.13
553,900280,골든센츄리,7740,160,2.1,8337436,64054040630,7580,8070,7370,230652000000,0.02,29800000,21502231,72.16
2,005380,현대차,132000,-1000,-0.8,478362,63868123000,133000,135500,132000,29076495228000,1.98,220276479,95229553,43.23
547,950140,잉글우드랩(Reg.S),13550,600,4.6,4323605,62384893050,13050,15450,12750,235311386700,0.02,17366154,15944139,91.81
1334,224060,코디엠,3480,540,18.4,17380148,61491818085,3120,3750,3085,78316982400,0.01,22504880,278840,1.24
488,006910,보성파워텍,5950,450,8.2,10594583,61378188830,5380,6070,5300,272835578050,0.02,45854719,69344,0.15
7,028260,삼성물산,128000,0,0.0,467719,60139604000,128000,130000,127500,24280325504000,1.65,189690043,17009224,8.97
22,011170,롯데케미칼,340000,18500,5.8,177336,59592490000,325500,343000,324000,11653642460000,0.79,34275419,10868816,31.71
1544,052600,한네트,5210,1130,27.7,11853601,58084338045,4210,5300,4180,60246877000,0.00,11563700,363945,3.15
23,009540,현대중공업,150000,8000,5.6,384857,57178895563,146500,151000,145500,11400000000000,0.78,76000000,11509653,15.14
11,090430,아모레퍼시픽,319000,-9000,-2.7,171276,54737434500,328000,328000,318000,18648258310000,1.27,58458490,21406029,36.62

In [84]:
# 등락률 내림차순 정리 
a_delta = a.sort_values(ascending = False, by = ['등락률'])
a_delta.head(n = 20)

,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수(천주),외국인 보유주식수,외국인 지분율(%)
1328,050890,쏠리드,3670,845,29.9,10012181,34444339900,2960,3670,2920,78814740020,0.01,21475406,0,0.00
1571,054340,엔알케이,2370,545,29.9,6228757,14397889635,2150,2370,2075,58265876460,0.00,24584758,173429,0.71
1544,052600,한네트,5210,1130,27.7,11853601,58084338045,4210,5300,4180,60246877000,0.00,11563700,363945,3.15
1955,086830,신양오라컴,620,114,22.5,10947986,6583458057,523,648,523,28066584080,0.00,45268684,182349,0.40
1888,101000,디엠씨,2695,450,20.0,7501892,19356922805,2220,2840,2215,34400664375,0.00,12764625,0,0.00
1334,224060,코디엠,3480,540,18.4,17380148,61491818085,3120,3750,3085,78316982400,0.01,22504880,278840,1.24
1714,010580,지코,1135,173,18.0,13478500,14833354587,963,1225,963,47343891800,0.00,41712680,229850,0.55
1376,084180,수성,9120,1390,18.0,501993,4328446580,7730,9120,7510,74784000000,0.01,8200000,185976,2.27
1784,094940,푸른기술,7510,1140,17.9,1286576,9454559430,6480,7900,6410,42365239270,0.00,5641177,32902,0.58
1185,031860,에이모션,5600,830,17.4,3840178,20525984615,4770,5850,4770,92266529600,0.01,16476166,314582,1.91
2168,091270,유디피,805,105,15.0,1601,1053605,658,805,658,5907294470,0.00,7338254,500,0.01
1999,114920,대주이엔티,6440,840,15.0,1,6440,6440,6440,6440,22343580000,0.00,3469500,0,0.00
2159,103660,씨앗,3220,420,15.0,106,340540,3220,3220,2440,6971235600,0.00,2164980,0,0.00
2091,223220,구름컴퍼니,3565,465,15.0,278,907105,3100,3565,3100,12121000000,0.00,3400000,7990,0.24
1925,243870,굿센,23000,3000,15.0,2,43000,20000,23000,20000,30956873000,0.00,1345951,0,0.00
2015,086220,네추럴FNP,2775,360,14.9,6,15330,2650,2775,2155,20491363125,0.00,7384275,0,0.00
2094,234100,세원,4040,525,14.9,271,1008440,3720,4040,3720,11877600000,0.00,2940000,0,0.00
2182,208890,에듀케이션파트너,2400,310,14.8,1,2400,2400,2400,2400,4777968000,0.00,1990820,0,0.00
2199,084440,유비온,1245,160,14.8,1000,1245000,1245,1245,1245,3731398215,0.00,2997107,0,0.00
2124,148780,비플라이소프트,10550,1350,14.7,1,10550,10550,10550,10550,10013469200,0.00,949144,0,0.00

In [89]:
# 외국인 지분율(%) 내림차순 정리 
a_foreigners = a.sort_values(ascending= False , by = ['외국인 지분율(%)'])
a_foreigners.head(n=20)

,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수(천주),외국인 보유주식수,외국인 지분율(%)
547,950140,잉글우드랩(Reg.S),13550,600,4.6,4323605,62384893050,13050,15450,12750,235311386700,0.02,17366154,15944139,91.81
1815,003925,남양유업우,244000,500,0.2,39,9433500,240000,244000,240000,40665528000,0.00,166662,151724,91.04
642,034950,한국기업평가,42900,50,0.1,790,33931200,42850,43050,42800,194788050600,0.01,4540514,3789259,83.45
168,051905,LG생활건강우,500000,1500,0.3,4166,2063670500,498000,500000,488000,1049848500000,0.07,2099697,1704962,81.20
479,002000,한국유리,27500,0,0.0,384,10564350,27500,27800,27100,277190650000,0.02,10079660,8133905,80.70
137,082640,동양생명,13300,400,3.1,110212,1458612050,12950,13350,12950,1430712787000,0.10,107572390,85444734,79.43
4,005935,삼성전자우,1361000,5000,0.4,50781,69712003688,1356000,1383000,1342000,27918774147000,1.90,20513427,16027181,78.13
28,010950,S-Oil,86000,2000,2.4,594029,51588460958,87800,87900,85800,9682120112000,0.66,112582792,86761841,77.06
176,003620,쌍용차,7210,-70,-1.0,136146,999438910,7280,7480,7180,989356892160,0.07,137220096,105295105,76.73
91,005385,현대차우,91800,-4000,-4.2,30438,2829486300,93700,94400,91600,2305096347600,0.16,25109982,18838821,75.03
553,900280,골든센츄리,7740,160,2.1,8337436,64054040630,7580,8070,7370,230652000000,0.02,29800000,21502231,72.16
66,005387,현대차2우B,95600,-3700,-3.7,66036,6418983200,99400,99700,95600,3595885494000,0.24,37613865,27137084,72.15
1074,900130,웨이포트,1865,-90,-4.6,4959971,9393296940,1930,1980,1825,104216200000,0.01,55880000,39054371,69.89
29,086790,하나금융지주,32300,150,0.5,711585,22975223650,32250,32500,32000,9560898902600,0.65,296003062,204002795,68.92
799,075180,새론오토모티브,7800,-40,-0.5,2079,16204860,7840,7850,7750,149760000000,0.01,19200000,13007833,67.75
10,055550,신한지주,43900,-200,-0.4,891693,39285398200,44550,44750,43600,20817361869300,1.42,474199587,319437928,67.36
102,090435,아모레퍼시픽우,190000,-4500,-2.3,12575,2411298500,194500,194500,190000,2005987700000,0.14,10557830,7042806,66.71
262,002960,한국쉘석유,448500,1000,0.2,1886,845070500,447500,449000,444500,583050000000,0.04,1300000,853410,65.65
152,051915,LG화학우,162500,-2000,-1.2,18468,3011702500,164500,166500,161000,1239699662500,0.08,7628921,4983722,65.33
832,092440,기신정기,4840,0,0.0,14750,71141780,4850,4860,4790,141328000000,0.01,29200000,18758218,64.24